### ISSUE TITLE
Incorrect ADC Measurements

### ISSUE THREAD

**Issue by sharrington93** [BuckeyeCurrent/Magic-CAN-Node#18]
### MCN 1 ###
AIN1 and AIN12 seem to be pulled high
GP1 is large number regardless of input

### MCN 2 ###
AIN5 and AIN8 are floating high
AIN4, AIN6, and AIN9 don't seem to be pulled down

This is an incomplete list.

**Comment by sharrington93** [comment]
### MCN 3 ###
AIN1, AIN12 are pulled high
AIN2, AIN4, AIN6, AIN7, AIN8, AIN11 don't seem to be pulled down
AIN6 and AIN7 are tied together

### MCN 4 ###
All of them are floating
AIN2 always 0 or floating

**Comment by sharrington93** [comment]
### MCN 5 ###
AIN3, AIN4, AIN5, AIN11 are floating
2V on AIN4 or AIN5 show 1V on AIN4 and AIN5

**Comment by Victorb101** [comment]
MCN 3

AIN-1 & AIN-12 were actually connected together (pulldowns in wrong orientation, resolved.

AIN-2, AIN-11, AIN-8, & AIN-8 pulldowns were missing a solder joint, resolved.

AIN-6 & AIN-7 were also connected together, resolved.

**Comment by Victorb101** [comment]
MCN 2

AIN-4, AIN-9, AIN-5, & AIN-8 missing pulldowns completely, resolved.

AIN-6 pulldown missing a solder joint, resolved.

**Comment by Victorb101** [comment]
MCN 5

AIN-5, AIN-3, AIN-11, & AIN-12 have bad solder joints on pulldowns, resolved.

@sharrington93 Not sure about AIN-4 behavior.  Check if it resolves itself.

**Comment by Victorb101** [comment]
MCN 5

Just noticed ADCINB1 & ADCINB2 were shorted together (AIN-4 & AIN-5).  Resolved

**Comment by Victorb101** [comment]
MCN 4

This is actually MCN Version 2.0, not Version 2.1.  It does not have pulldowns.  We should not use this on the bike.  We will only use MCNs Version 2.1 or greater.

**Comment by Victorb101** [comment]
MCN 1

AIN-1 & AIN-12 pulldowns installed in wrong orientation, resolved.

**Comment by sharrington93** [comment]
### MCN 5 ###
Works

### MCN 3 ###
Works

### MCN 2 ###
Works

### MCN 1 ###
Works

**Comment by Victorb101** [comment]
@sharrington93 Can you close this issue?

**Comment by aaronbeekay** [comment]
I will go ahead and close this.
